### PR TITLE
adjust menu and update company of the organizers

### PR DESCRIPTION
**Pull request by daviguelfi**
I made this little changes because I think that's better for the UI

### CODE REVIEW

**Comment by duduribeiro** [comment]
👏  🏅 congratz

**Comment by duduribeiro** [comment]
@daviguelfi o @marquesds está trampando no Gympass agora.. consegue mudar?

**Comment by duduribeiro** [comment]
já aproveita e coloca vc tb 😂

**Comment by daviguelfi** [comment]
@duduribeiro mudo sim

**Pull request merged**
